### ISSUE TITLE
[Feature Request] Add ability to change tmdb api key in settings

### ISSUE THREAD

**Issue by chrysos349** [aleiepure/ticketbooth#10]
What about adding a setting to supply your own TMBD api key? For now it's hard-coded in `ticketbooth` executable.

**Comment by yochananmarqos** [comment]
There is no TMDB API key hard-coded anywhere, you'll need to provide your own. Anyway, the binary is just a Python script, not a compiled binary.

It's[ looking for](https://github.com/aleiepure/ticketbooth/blob/v1.0.1/src/providers/tmdb_provider.py#L27) an erroneous `TMDB_KEY` environment variable, however it should be looking for `TMDB_API_KEY`.

I can launch it fine with no errors using my API key I created with the proper variable.

See: https://github.com/celiao/tmdbsimple#api-key

**Comment by chrysos349** [comment]
@yochananmarqos never mind. It was the network issue. Could you add a setting to supply my own key?

> There is no TMDB API key hard-coded anywhere

Yes, there is. The app is launched via the script below. The api key is hard-coded. 

https://github.com/aleiepure/ticketbooth/blob/5c97745ceeb2a2b165f779a3cdf37817b4ec99ed/install/ticketbooth-run-script.in#L6


> It's[ looking for](https://github.com/aleiepure/ticketbooth/blob/v1.0.1/src/providers/tmdb_provider.py#L27) an erroneous TMDB_KEY environment variable, however it should be looking for TMDB_API_KEY.

No, it's not. At least not your app. I'm not talking about a python3 module.

https://github.com/aleiepure/ticketbooth/blob/5c97745ceeb2a2b165f779a3cdf37817b4ec99ed/src/providers/tmdb_provider.py#L27

**Comment by yochananmarqos** [comment]
Ah, that's what I get for building from source and not looking at the Flatpak, I guess. The developer purposely created the `TMDB_KEY` custom variable for the run script. Nevermind me, sorry about the noise.

**Comment by chrysos349** [comment]
@yochananmarqos 
> that's what I get for building from source and not looking at the Flatpak

So did I, but I referenced the flatpak template.

P.S. And I realized you're not the app creator.

**Comment by aleiepure** [comment]
First of all, thanks for the feedback. 
As a reminder, the only supported way to run Ticket Booth is via Flatpak. 
I confirmed with TMDB that the built-in key is functioning properly and is not blocked.
A setting to provide your own API key is already in the works and is going to be available in the next release.
