### ISSUE TITLE
Padding in screenshots make appstream validation fail

### ISSUE THREAD

**Issue by a-wai** [aleiepure/ticketbooth#13]
**Describe the issue**
Appstream validation fails due to invalid screenshots.

**To Reproduce**
Build the application manually using `meson` and `ninja` then execute `meson test`. The appstream validation test fails with the following output:

```
==================================== 3/3 =====================================
test:         Validate appstream file
start time:   09:35:01
duration:     1.71s
result:       exit status 1
command:      MALLOC_PERTURB_=98 /usr/bin/appstream-util validate data/me.iepure.Ticketbooth.metainfo.xml
----------------------------------- stdout -----------------------------------
data/me.iepure.Ticketbooth.metainfo.xml: FAILED:
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/aleiepure/ticketbooth/main/data/appstream/1.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/aleiepure/ticketbooth/main/data/appstream/1.png]
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/aleiepure/ticketbooth/main/data/appstream/2.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/aleiepure/ticketbooth/main/data/appstream/2.png]
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/aleiepure/ticketbooth/main/data/appstream/3.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/aleiepure/ticketbooth/main/data/appstream/3.png]
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/aleiepure/ticketbooth/main/data/appstream/4.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/aleiepure/ticketbooth/main/data/appstream/4.png]
----------------------------------- stderr -----------------------------------
Validation of files failed
==============================================================================
```

**Expected behavior**
Appstream validation should succeed

**Operating system (please complete the following information):**
 - Distro: Debian
 - Version: 1.0.1
 - Desktop Environment: XFCE
 - Xorg/Wayland: Xorg

**Additional context**
- [x] I am aware that this application uses content from third parties and I am not reporting issues about their data (wrong or missing data and/or images). If the latter is the case, please report directly to them.

**Comment by aleiepure** [comment]
The error is because the images are not in a 16:9 aspect ratio and can be safely ignored. 
Testing with `appstreamcli`, the upstream version of `appstream-util`, does not report any issues. As a reminder, the only supported way to run Ticket Booth is via Flatpak, and because Flatpak uses the first utility, that's enough for me.
I don't want to seem selfish, but I don't have the material time to debug issues related to environments different than the one I'm developing for, sorry.

**Comment by a-wai** [comment]
> Testing with `appstreamcli`, the upstream version of `appstream-util`

Maybe `s/appstream-util/appstreamcli/` in https://github.com/aleiepure/ticketbooth/blob/main/data/meson.build#L35 would make sense then, in order to avoid any confusion? AFAIU `appstream-util` is a different software provided by https://github.com/hughsie/appstream-glib which, as such, isn't guaranteed to yield the same results as `appstreamcli`, so any user trying to build the software themselves for $reason could run into this issue.
