### ISSUE TITLE
[Feature request] 'Watched' filter

### ISSUE THREAD

**Issue by rene-coty** [aleiepure/ticketbooth#14]
For the moment being, marking a movie as watched doesn't differenciate it from the others (no specific icon/category)
Adding a filter to only display films that have been marked as 'Watched', or those who have not yet been watched at all would be helpful to give this functionality more sense + it would be a welcomed help to easily sort/simplify the watchlist

**Comment by aleiepure** [comment]
Fixed in 85461dd
