### ISSUE TITLE
Frequent crashs of the application

### ISSUE THREAD

**Issue by Philetjosie** [aleiepure/ticketbooth#20]
I just have started using Ticket booth, therefore I had to import around 30 / 40 movies. But each 2 to 5 imports, the application close without warning. The importation is succesfull, but each time I have to restart the application to continue. It's really painfull.
I do not know if there is a log file somewhere, tell me, so that I can share it with you.

OS: ubuntu 2023.04, ticket booth installed from flathub

**Comment by aleiepure** [comment]
Thank you for your feedback. I am aware of the issue and I am doing my best to investigate and fix the issue as soon as possible. 
The Flathub build does not have any logging ability. I have introduced it in 1eea79b.
To keep the issues section more organized, I am closing this. We can continue the discussion on #21.
