### ISSUE TITLE
Constant crashing of the app

### ISSUE THREAD

**Issue by madagaskarsky** [aleiepure/ticketbooth#21]
**Describe the issue**
After adding 2-5 titles the app hangs and then crashes.

**To Reproduce**
1. Start the app fresh
2. Add a few titles
3. The app hangs and then crashes after an unusual spike in CPU I/O wait

**Expected behavior**
The app should not crash

**Screenshots**
![Screenshot from 2023-10-01 03-29-33](https://github.com/aleiepure/ticketbooth/assets/13730211/124f4f0a-b24f-4b57-af5a-10daff57fb7f)

In the attached image, within the red circle, you can see the cpu I/O wait spike. It's the white tip. The blue circle is the network usage when the app was pulling the data for the requested titles. The last box with the white/orange tips is the actual IO write to the disk. 

**Operating system (please complete the following information):**
 - Distro: Fedora Silverblue
 - Version: 38.20230922
 - Desktop Environment: Gnome 44.5
 - Xorg/Wayland: Wayland

**Comment by aleiepure** [comment]
Thank you for your feedback. I am aware of the issue and I am investigating the problem. I will try to fix it as soon as possible

**Comment by madagaskarsky** [comment]
Thank you for your work on this app. This is a very beautiful looking app and has helped me log my watchlist for the first time without having to create online accounts. I am very excited for the future of this app.

**Comment by aleiepure** [comment]
Commit 89bb326 fixes crashes, high usage peaks, and random UI blanking (issue #9). It will be soon available on Flathub as an update.
