### ISSUE TITLE
Watched Status Gets Reset After Metadata Update

### ISSUE THREAD

**Issue by june128** [aleiepure/ticketbooth#23]
**Describe the issue**

Whenever I update the metadata of a TV series or movie the watched status gets reset.

**To Reproduce**
1. Go to a TV series or movie.
2. Mark it as watched.
3. Click the "Update Metadata" button.
4. Observe that the watched status is now reset.

**Expected behavior**
I expect the watched status to survive a metadata update.

**Operating system (please complete the following information):**
 - Distro: Arch Linux
 - Version: rolling
 - Desktop Environment: GNOME 44.5
 - Xorg/Wayland: Wayland

**App version:**
1.0.3.1

**Additional context**
- [x] I am aware that this application uses content from third parties and I am not reporting issues about their data (wrong or missing data and/or images). If the latter is the case, please report directly to them.

**Comment by aleiepure** [comment]
I can confirm movies are not affected any more thanks to #28. I've also implemented the fix for TV Series but am still testing it.
I'll close this issue as soon I can confirm it works fine.
Thanks for your feedback

**Comment by aleiepure** [comment]
Everything is working as aspected.

**Comment by june128** [comment]
Awesome, thanks!
