### ISSUE TITLE
Cannot add TV serie from TMDB

### ISSUE THREAD

**Issue by thomasnaudin** [aleiepure/ticketbooth#34]
**Describe the issue**
One cannot add TV serie from TMDB.

**To Reproduce**
1. Add TV serie from TMDB
2. The search function works
3. Confirmation message shows up
4. Error message in terminal
5. No serie added in watchlist

**Expected behavior**
Selected serie should be added to watchlist.
An error should be displayed if data cannot be fetched from TMDB.

**Stacktrace**

```
(ticketbooth-bin:2): Gtk-CRITICAL **: 13:30:59.174: gtk_list_box_row_grab_focus: assertion 'box != NULL' failed
Traceback (most recent call last):
  File "/app/share/ticketbooth/src/background_queue.py", line 80, in _run_in_thread
    outcome = self.task_function(self)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/ticketbooth/src/widgets/search_result_row.py", line 180, in _add_content_to_db
    local.add_content(id=self.tmdb_id, media_type=self.media_type)
  File "/app/share/ticketbooth/src/providers/local_provider.py", line 346, in add_content
    return LocalProvider.add_series(id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/ticketbooth/src/providers/local_provider.py", line 274, in add_series
    serie = SeriesModel(tmdb.get_serie(id))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/ticketbooth/src/models/series_model.py", line 94, in __init__
    self.seasons = self._parse_seasons(d['seasons'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/ticketbooth/src/models/series_model.py", line 189, in _parse_seasons
    seasons.append(SeasonModel(show_id=self.id, d=season))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/ticketbooth/src/models/season_model.py", line 90, in __init__
    tmdb.TMDBProvider.get_season_episodes(show_id, self.number))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/ticketbooth/src/providers/tmdb_provider.py", line 117, in get_season_episodes
    return tmdb.TV_Seasons(id, season).info(language=lang)['episodes']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/tmdbsimple/tv.py", line 524, in info
    response = self._GET(path, kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/tmdbsimple/base.py", line 110, in _GET
    return self._request('GET', path, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/tmdbsimple/base.py", line 105, in _request
    response.raise_for_status()
  File "/app/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/tv/79501/season/0?language=fr&api_key=3cea7ff23278a75460ead4d6e2cef9af
```

**Operating system (please complete the following information):**
 - Distro: Fedora
 - Version: 38
 - Desktop Environment: Gnome 44
 - Xorg/Wayland: Wayland

**Additional context**
- [x] I am aware that this application uses content from third parties and I am not reporting issues about their data (wrong or missing data and/or images). If the latter is the case, please report directly to them. 

JSON response when GET on TMDB url :

```json
{"success":false,"status_code":6,"status_message":"Invalid id: The pre-requisite id is invalid or not found."}
```

**Comment by gnesterif** [comment]
The problem are the specials, they get stored in a season 0 which seems to make trouble since today [(see here)](https://www.themoviedb.org/talk/653119157eb5f2013bae0006)

**Comment by aleiepure** [comment]
As @gnesterif said, the problem is not related to Ticket Booth directly but is on TMDB’s side.
There are no listed updates to the API so the cause is unknown. I’ll do my best to keep this issue updated with news from the provider.

**Comment by aleiepure** [comment]
It seems that they started a migration of TV series lists (something Ticket Booth does not use) last night and is still ongoing. Probably the server borked some data and the other api endpoints are unable to get them. See [here](https://status.themoviedb.org).

**Comment by aleiepure** [comment]
The migration has been completed and the API endpoint is once again fully operational.
