### ISSUE TITLE
[Bug] Stuck on "Getting things ready" screen

### ISSUE THREAD

**Issue by stpnwf** [aleiepure/ticketbooth#35]
**Describe the issue**
Ticketbooth keeps loading forever after launch. 
**To Reproduce**
1. Install on Fedora 38
2. Launch app
3. See issue

**Screenshots**

![Screenshot from 2023-10-21 09-27-12-obfuscated](https://github.com/aleiepure/ticketbooth/assets/81482539/39407ba8-2117-44f2-8ced-5c2aeec93fb3)

**Operating system (please complete the following information):**
 - Distro: Fedora
 - Version: 38
 - Desktop Environment: Gnome
 - Xorg/Wayland: Wayland

**Additional context**
- [x] I am aware that this application uses content from third parties and I am not reporting issues about their data (wrong or missing data and/or images). If the latter is the case, please report directly to them. 

I left it open for 10+ minutes /restarted it and it always hangs on that window.

**Comment by aleiepure** [comment]
The "Getting things ready" screen should appear only on the first launch, is this the case or not?
During this phase, the app downloads some data from TMDB's API which recently had issues. I cannot replicate the issue with the same setup, maybe you tried while they were down or there are still some lingering issues.
Nevertheless, delete `~/.var/app/me.iepure.Ticketbooth/data/data.db` and restart the app (you will lose your watchlist if it is present). Now it should be able to finish the setup and go to the main screen.
Feel free to close this issue if it is fixed or let me know if you keep experiencing the same problem.

**Comment by stpnwf** [comment]
Awesome, deleting that file fixed it. Thanks for the help.
