### ISSUE TITLE
Adding movies from TMDB not working

### ISSUE THREAD

**Issue by manikandancode** [aleiepure/ticketbooth#6]
Keep loading without any end. 

OS: Ubuntu 23.04 (Wayland)
Flatpak

![Screenshot from 2023-09-25 16-12-50](https://github.com/aleiepure/ticketbooth/assets/46480489/75bc6f83-bbe3-4157-bbe9-8693553f142d)

![Screenshot from 2023-09-25 16-13-07](https://github.com/aleiepure/ticketbooth/assets/46480489/557fd54c-1a1d-4833-a0db-87eefa9ad691)

**Comment by aleiepure** [comment]
I've released v1.0.1 on [Flathub](https://flathub.org/it/apps/me.iepure.Ticketbooth) (should be available in a few hours) to fix your issue. Thanks for your feedback.
