### ISSUE TITLE
UI freezes / blank screen

### ISSUE THREAD

**Issue by rene-coty** [aleiepure/ticketbooth#9]
**Describe the issue**
After some usage the UI becomes irresponsive and 'disappears' 

**To Reproduce**
1. Add some movies from TMDB
2. While adding movies you'll notice that the main window behind may eventually display a 'blank page' after a few additions

**Expected behavior**

Addition process should end without errors

**Screenshots**

Blank app → user is forced to quit and restart the app

![Capture d’écran du 2023-09-25 19-25-45](https://github.com/aleiepure/ticketbooth/assets/95506494/845f6d57-6115-42cb-bd00-8554d902a7e7)

**Operating system (please complete the following information):**
 - Distro: Fedora 38 
 - Desktop Environment: GNOME 44 
 - Wayland 

**Additional context**
- [x] I am aware that this application uses content from third parties and I am not reporting issues about their data (wrong or missing data and/or images). If the latter is the case, please report directly to them.

**Comment by aleiepure** [comment]
I was made aware of the issue after the app went live on Flathub. Unfortunately, this bug presents itself quite randomly and is difficult to investigate. I will do my best to fix it as soon as possible.
The app has not crashed, and the widgets are still there and work as they should (clicking in the right spots will trigger the correct behavior), but they just decide to become invisible. 
> [!NOTE]  
> As a temporary workaround try resizing the window, everything will pop into place again.

**Comment by aleiepure** [comment]
Commit f631e02 should fix the issue. I've tested it on my and on some friends' machines and no one could trigger the weird behavior.
I'll leave this issue open for now.

**Comment by aleiepure** [comment]
Commit 89bb326 once and for all, fixes all crashes, high usage peaks, and random UI blanking present in the stable release. It will be soon available on Flathub as an update.
